/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Build RAG Applications using MongoDB",
  "tagline": "",
  "url": "https://ai-rag-lab.github.io",
  "baseUrl": "/ai-rag-lab/",
  "projectName": "mongodb-developer.github.io",
  "organizationName": "mongodb-developer",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.svg",
  "deploymentBranch": "gh-pages",
  "staticDirectories": [
    "static"
  ],
  "customFields": {
    "startButtonTitle": "Start Lab",
    "featureList": [
      {
        "title": "Hands-On Experiences",
        "illustration": "img/coding.png",
        "description": "\n        Learn by doing, not by reading.\n    "
      },
      {
        "title": "Amazing Instructors",
        "illustration": "img/highfive.png",
        "description": "\n        Build it with the help of our amazing instructors, or just do it on your own.\n    "
      },
      {
        "title": "Take-Home Material",
        "illustration": "img/writing.png",
        "description": "\n        Take home the material and keep learning.\n    "
      }
    ],
    "utmParams": "utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=ai_rag_lab&utm_term=apoorva.joshi"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/ramiro.enriquez/Documents/Code/ai-rag-lab/sidebars.js",
          "editUrl": "https://github.com/mongodb-developer/ai-rag-lab/blob/main"
        },
        "theme": {
          "customCss": "/Users/ramiro.enriquez/Documents/Code/ai-rag-lab/src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-ZJ28V71VTQ",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "plugins": [
    "/Users/ramiro.enriquez/Documents/Code/ai-rag-lab/node_modules/docusaurus-lunr-search/src/index.js"
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": true
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "Build RAG Applications using MongoDB",
      "logo": {
        "alt": "MongoDB Logo",
        "src": "img/logo.svg",
        "srcDark": "img/logo-dark.svg",
        "className": "navbar-logo",
        "width": "135px",
        "height": "100%"
      },
      "items": [],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "label": "Try MongoDB Atlas",
          "href": "https://www.mongodb.com/try?utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=ai_rag_lab&utm_term=apoorva.joshi"
        },
        {
          "label": "Developer Center",
          "href": "https://www.mongodb.com/developer/utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=ai_rag_lab&utm_term=apoorva.joshi"
        },
        {
          "label": "GenAI Code Examples",
          "href": "https://github.com/mongodb-developer/GenAI-Showcase"
        },
        {
          "label": "GenAI Forums",
          "href": "https://www.mongodb.com/community/forums/c/generative-ai/162/utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=ai_rag_lab&utm_term=apoorva.joshi"
        },
        {
          "href": "https://github.com/mongodb-developer/ai-rag-lab",
          "label": "This lab in GitHub"
        },
        {
          "label": "© 2025 MongoDB, Inc.",
          "href": "#"
        }
      ]
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "powershell",
        "swift",
        "kotlin"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
